"""Admin B2C communication record — ``/api/admin/communication/*``. Phase 7 of
the B2C Admin Portal build-out. READ-ONLY: see
``customer_communication_admin_service``'s module docstring for why there is no
compose, no ticket reply and no chat handling here (notifications are
system-generated by design, the ticket channel is retired, and Live Support is
where chats are answered).

Gated on `customer.view`, the same code the other B2C desks use. Admin only.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from app.auth.rbac import P, require
from app.database.session import get_db
from app.models_v2 import User
from app.schemas.customer_communication_admin import ChatOverview, NotificationList, TicketDetail, TicketList
from app.services import customer_communication_admin_service as service

router = APIRouter(prefix="/api/admin/communication", tags=["admin-communication"])


@router.get(
    "/notifications", response_model=NotificationList,
    summary="Notifications sent to customers",
    description=(
        "Requires `customer.view` (admin only). Newest first. Every one was written by the "
        "event it describes (a booking, a cancellation, a payment); `summary` covers the whole "
        "log regardless of filters."
    ),
)
def list_notifications(
    db: Session = Depends(get_db),
    _: User = Depends(require(P.CUSTOMER_VIEW)),
    page: int = Query(1, ge=1),
    page_size: int = Query(25, ge=1, le=200),
    notification_type: str | None = Query(None, alias="type"),
    is_read: bool | None = Query(None, alias="read"),
    search: str | None = Query(None, max_length=120),
):
    if notification_type and notification_type not in service.NOTIFICATION_TYPES:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, f"Unknown type {notification_type!r}.")
    return service.list_notifications(
        db, page=page, page_size=page_size, notification_type=notification_type,
        is_read=is_read, search=search,
    )


@router.get(
    "/tickets", response_model=TicketList, summary="Legacy support tickets (history only)",
    description=(
        "Requires `customer.view` (admin only). The customer site now uses live chat, so "
        "tickets are no longer created; existing ones are listed for history."
    ),
)
def list_tickets(
    db: Session = Depends(get_db),
    _: User = Depends(require(P.CUSTOMER_VIEW)),
    page: int = Query(1, ge=1),
    page_size: int = Query(25, ge=1, le=200),
    ticket_status: str | None = Query(None, alias="status"),
    priority: str | None = Query(None),
    search: str | None = Query(None, max_length=120),
):
    if ticket_status and ticket_status not in service.TICKET_STATUSES:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, f"Unknown status {ticket_status!r}.")
    if priority and priority not in service.TICKET_PRIORITIES:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, f"Unknown priority {priority!r}.")
    return service.list_tickets(
        db, page=page, page_size=page_size, ticket_status=ticket_status, priority=priority, search=search,
    )


@router.get(
    "/tickets/{ticket_id}", response_model=TicketDetail, summary="One legacy ticket with its thread",
    description="Requires `customer.view` (admin only).", responses={404: {"description": "No such ticket."}},
)
def get_ticket(ticket_id: int, db: Session = Depends(get_db), _: User = Depends(require(P.CUSTOMER_VIEW))):
    row = service.get_ticket(db, ticket_id)
    if row is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "No such ticket.")
    return row


@router.get(
    "/chat-overview", response_model=ChatOverview, summary="Live chat and call totals",
    description=(
        "Requires `customer.view` (admin only). A summary only — chats are answered on the "
        "Live Support desk."
    ),
)
def chat_overview(db: Session = Depends(get_db), _: User = Depends(require(P.CUSTOMER_VIEW))):
    return service.chat_overview(db)
