"""add sequences for request / ticket / invoice numbers

Revision ID: 0028_doc_sequences
Revises: 0027_seed_catalog
Create Date: 2026-07-29

Document numbers were generated by counting existing rows:

    count = SELECT count(*) FROM service_requests WHERE request_number LIKE 'TKT-%'
    number = f"TKT{year}-{count + 1:06d}"

Two defects, both caught by running the lifecycle test twice:

1. **Wrong column.** Ticket and invoice numbers are stored in
   ``ticket_number`` / ``invoice_number``, but the count filtered on
   ``request_number``. It therefore always returned 0, always produced
   ``...-000001``, and the second ticket ever issued failed on
   ``uq_sr_ticket_number``. Only the very first ticket could be issued.

2. **Race.** Even against the right column, count-then-insert is not atomic;
   two concurrent issuances would read the same count and collide.

PostgreSQL sequences fix both: allocation is atomic, never reuses a value,
and does not depend on what is already stored. Sequences are not tables, so
the nine-table design is unaffected.
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0028_doc_sequences"
down_revision: Union[str, None] = "0027_seed_catalog"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SEQUENCES = (
    "seq_request_number",
    "seq_service_request_number",
    "seq_ticket_number",
    "seq_invoice_number",
)


def upgrade() -> None:
    for name in SEQUENCES:
        op.execute(f"CREATE SEQUENCE IF NOT EXISTS {name} START WITH 1 INCREMENT BY 1")

    # Existing rows were numbered by the old counter; start each sequence
    # above the highest value already in use so a fresh allocation cannot
    # collide with seeded or previously-issued documents.
    op.execute(
        """
        SELECT setval(
            'seq_request_number',
            GREATEST(COALESCE((
                SELECT MAX(NULLIF(regexp_replace(request_number, '\\D', '', 'g'), '')::bigint)
                FROM service_requests WHERE request_number LIKE 'REQ-%'
            ), 0), 1)
        )
        """
    )


def downgrade() -> None:
    for name in SEQUENCES:
        op.execute(f"DROP SEQUENCE IF EXISTS {name}")
