# -*- coding: utf-8 -*-
"""Generate a SCOPED copy of the Merchant Portal stylesheet for embedding elsewhere.

    python scripts/build_classic_embed_css.py

WHY THIS EXISTS
---------------------------------------------------------------------------
The Admin Portal's Manual Enquiry screen mounts the REAL Merchant Portal
booking-enquiry form — the same classic-enquiry.js, not a copy — so it has to
carry the same styles or it would render as unstyled markup.

It cannot simply link classic.css. That file opens with a full reset:

    :root{...}  *{...}  html,body{...}  button{...}  a{...}  h1..h5{...}
    table{...}  select{...}  textarea{...}

Loading it into the Admin Portal would restyle the entire portal — its body
font, every heading, every button and link. That is precisely the "do not
redesign the Admin Portal" line.

So this script rewrites every selector to sit under one wrapper class. Inside
`.cl-embed` the form looks exactly as it does in the Merchant Portal; outside
it, nothing changed at all.

WHY GENERATED RATHER THAN HAND-WRITTEN
---------------------------------------------------------------------------
Hand-extracting the ~274 rules the form touches would be a second stylesheet to
keep in step with the first, and it would drift the first time someone restyled
a control in classic.css. This is mechanical and repeatable: re-run it whenever
classic.css changes and the embedded form follows.

WHAT IT DOES NOT TOUCH
`@keyframes` names are left alone. They are already `cl`-prefixed in classic.css
and renaming them would break the animations that reference them.
"""
from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "frontend", "merchant-classic", "css", "classic.css")
OUT = os.path.join(ROOT, "frontend", "assets", "css", "classic-embed.css")

SCOPE = ".cl-embed"

#: Selectors that mean "the document" in the source and must mean "the wrapper"
#: here. `*` is handled separately — it becomes a descendant selector.
DOCUMENT_SELECTORS = {":root", "html", "body", "html,body", ":host"}

HEADER = f"""/* GENERATED by scripts/build_classic_embed_css.py — do not edit by hand.
   Source: frontend/merchant-classic/css/classic.css

   The Merchant Portal's stylesheet, with every selector scoped under
   `{SCOPE}` so the Admin Portal can mount the real booking-enquiry form
   without inheriting the Merchant Portal's reset.

   Re-run the script after changing classic.css. */

"""


def scope_selector(sel: str) -> str:
    """One selector -> the same selector under the wrapper."""
    sel = sel.strip()
    if not sel:
        return sel
    # Already ours.
    if sel.startswith(SCOPE):
        return sel
    # The document-level selectors become the wrapper itself, so the reset and
    # the custom properties apply to the embedded subtree and nothing else.
    if sel in DOCUMENT_SELECTORS:
        return SCOPE
    # `*` and `*::before` style resets become descendants of the wrapper.
    if sel.startswith("*"):
        return f"{SCOPE} {sel}"
    # A bare element selector (button, a, h1, select…) likewise.
    return f"{SCOPE} {sel}"


def scope_block(css: str) -> str:
    """Rewrite selectors at one nesting level, recursing through @media/@supports."""
    out = []
    i = 0
    n = len(css)
    while i < n:
        # Whitespace and comments are emitted as-is. This has to happen BEFORE
        # the at-rule test: `@media` is almost never the first character after
        # the previous rule, and testing css[i] == "@" against a newline made
        # every media query parse as a selector — which produced the nonsense
        # `.cl-embed @media (...)` and left its contents unscoped.
        lead_m = re.match(r"(\s|/\*.*?\*/)+", css[i:], re.S)
        if lead_m:
            out.append(lead_m.group(0))
            i += lead_m.end()
            if i >= n:
                break

        # at-rules
        if css[i] == "@":
            # find the at-rule name and its block (or statement)
            m = re.match(r"@([\w-]+)([^;{]*)([;{])", css[i:])
            if not m:
                out.append(css[i])
                i += 1
                continue
            name, params, terminator = m.group(1), m.group(2), m.group(3)
            if terminator == ";":
                out.append(css[i:i + m.end()])
                i += m.end()
                continue
            # a block at-rule: find its matching brace
            start = i + m.end()
            depth = 1
            j = start
            while j < n and depth:
                if css[j] == "{":
                    depth += 1
                elif css[j] == "}":
                    depth -= 1
                j += 1
            inner = css[start:j - 1]
            if name.lower() in ("media", "supports", "layer", "container"):
                inner = scope_block(inner)          # recurse: selectors inside are real
            # keyframes / font-face / property: contents are not selectors
            out.append(f"@{name}{params}{{{inner}}}")
            i = j
            continue

        # a rule: selector list up to '{'
        brace = css.find("{", i)
        if brace == -1:
            out.append(css[i:])
            break
        selectors = css[i:brace]
        # keep any comment/whitespace that precedes the selector list
        lead = ""
        cm = re.match(r"\s*(/\*.*?\*/\s*)*", selectors, re.S)
        if cm:
            lead = cm.group(0)
            selectors = selectors[cm.end():]

        depth = 1
        j = brace + 1
        while j < n and depth:
            if css[j] == "{":
                depth += 1
            elif css[j] == "}":
                depth -= 1
            j += 1
        body = css[brace + 1:j - 1]

        if selectors.strip():
            scoped = ", ".join(scope_selector(s) for s in selectors.split(",") if s.strip())
            out.append(f"{lead}{scoped}{{{body}}}")
        else:
            out.append(f"{lead}{{{body}}}")
        i = j
    return "".join(out)


def main() -> int:
    if not os.path.exists(SRC):
        print(f"source stylesheet not found: {SRC}")
        return 2
    css = open(SRC, encoding="utf-8").read()
    scoped = scope_block(css)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER + scoped)

    rules_in = css.count("{")
    rules_out = scoped.count("{")
    print(f"  source : {os.path.relpath(SRC, ROOT)}  ({rules_in} blocks)")
    print(f"  output : {os.path.relpath(OUT, ROOT)}  ({rules_out} blocks)")
    if rules_in != rules_out:
        print(f"  ! block count changed ({rules_in} -> {rules_out}) — inspect the output")
        return 1
    # Nothing may reach outside the wrapper. Two things are legitimately
    # unscoped and must not be reported: comment text that happens to contain a
    # brace, and the `0%`/`70%`/`to` stops inside @keyframes, which are not
    # selectors at all and would break the animation if prefixed.
    bare = re.sub(r"/\*.*?\*/", "", scoped, flags=re.S)
    bare = re.sub(r"@keyframes[^{]*\{(?:[^{}]*\{[^{}]*\})*[^{}]*\}", "", bare, flags=re.S)
    stray = [s for s in re.findall(r"(?:^|[}{])\s*([^{}@]+)\{", bare)
             if s.strip() and SCOPE not in s]
    print(f"  selectors outside {SCOPE}: {len(stray)}")
    if stray:
        for s in stray[:5]:
            print(f"      {s.strip()[:70]}")
        return 1
    return 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    raise SystemExit(main())
