# -*- coding: utf-8 -*-
"""Vendor the homepage hero photograph from Wikimedia Commons.

    python scripts/fetch_hero_image.py

The sibling of fetch_destination_images.py, and it holds the same line: the
licence gate is that script's (imported, not copied), nothing hotlinks, and the
credit is regenerated from live Commons metadata rather than written by hand.

WHY THIS PHOTOGRAPH. The hero is a full-viewport, dark, cinematic frame with
white type across its upper half, so the brief is: a real destination this
business sells, a dark sky with room for a headline, the subject near the
centre (a phone crops a landscape frame to its middle quarter), and at least
2560px wide. Downtown Dubai at blue hour - the Burj Khalifa and the skyline
doubled in still water - is all of that, and it is CC0.

Three widths, no crop: the page sets it with object-fit: cover, and the
composition holds at every aspect ratio from 21:9 down to a 9:19.5 phone
because the tower is on the centre line.
"""

from __future__ import annotations

import io
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from fetch_hotel_images import download, fetch_metadata, licence_ok  # noqa: E402

TITLE = "File:Dubai skyline unsplash.jpg"
SLUG = "hero-dubai"
OUT_DIR = os.path.join(ROOT, "frontend", "assets", "images")
CREDITS = os.path.join(OUT_DIR, "CREDITS.md")
WIDTHS = (2560, 1600, 960)
WEBP_QUALITY = 78


def main() -> int:
    meta = fetch_metadata(TITLE, max(WIDTHS))
    if not licence_ok(meta["licence"]):
        print(f"licence refused: {meta['licence']}")
        return 1
    img = Image.open(io.BytesIO(download(meta["thumb_url"]))).convert("RGB")
    for width in WIDTHS:
        height = round(img.height * width / img.width)
        path = os.path.join(OUT_DIR, f"{SLUG}-{width}.webp")
        img.resize((width, height), Image.LANCZOS).save(path, "WEBP", quality=WEBP_QUALITY, method=6)
        print(f"  {os.path.basename(path)}  {width}x{height}  {os.path.getsize(path) // 1024} KB")
    artist = (meta["artist"] or "Unknown").replace("|", "/")
    with open(CREDITS, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join([
            "# Image credits",
            "",
            "Generated by `scripts/fetch_hero_image.py` from Wikimedia Commons",
            "metadata. Do not edit by hand - re-run the script instead.",
            "",
            "| File | Photographer | Licence | Source |",
            "| --- | --- | --- | --- |",
            f"| `{SLUG}-*.webp` | {artist} | {meta['licence']} | [{meta['title']}]({meta['descr_url']}) |",
            "",
        ]))
    print(f"ok  {meta['licence']}  {artist[:60]}")
    return 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    raise SystemExit(main())
