'use strict';
/* ops-api.js — the Operations Portal's backend contract, in one place.
   ===========================================================================
   VERSION 2 (frontend/operations/) talks to the backend exclusively through
   this file. It is a TRANSPORT LAYER ONLY: no endpoint, payload shape, schema,
   permission or business rule is invented here. Every function below maps 1:1
   onto a route that is already registered in backend/app/main.py.

   WHY A SECOND FILE NEXT TO merchant-api.js
   merchant-api.js covers exactly the merchant slice the Classic merchant UI
   needs. The Operations Portal is the whole platform — admin, super admin,
   approvals, payment verification, merchant lifecycle, audit — so it needs
   the rest of the surface too. merchant-api.js is NOT modified and NOT loaded
   by the Operations Portal; the two files are independent and either can
   change without touching the other.

   HOW THIS LIST WAS PRODUCED
   Transcribed from the live OpenAPI document (71 paths) generated by
   `app.openapi()` on 2026-07-30, cross-read against each router's
   `Depends(require(...))` so the permission code required by every call is
   recorded next to it. The portal uses those codes to decide what to render,
   which is why they live here rather than being guessed in a screen file.

   ONLY ROUTERS REGISTERED IN main.py EXIST. The repo contains ~23 router
   modules but only 11 are included (the v2 schema port is incomplete — see
   /api/status). Anything not below is a 404 today, however plausible the
   filename in backend/app/routers/ looks.

   Requires, in this order: axios, then ops-core.js (for OPS_API_BASE and
   opsAuthHeaders()). Errors are re-thrown untouched so callers can read
   err.response.data.detail, which is what FastAPI returns.               */

const OpsApi = {
  /* Single choke point: base URL, bearer token and error shape in one place.
     The token comes from whichever portal namespace this session signed in
     under (merchant / admin / super_admin) — see opsAuthHeaders(). */
  async _req(method, path, { params, data, responseType } = {}) {
    const res = await axios({
      method,
      url: `${OPS_API_BASE}${path}`,
      headers: opsAuthHeaders(),
      params,
      data,
      responseType,
    });
    return res.data;
  },

  /* ==================================================================== */
  /* Identity                                                             */
  /* ==================================================================== */

  /* The authority on what this session may do. `permissions` is the union of
     role defaults + merchant sub-role defaults + per-user grants, computed
     server-side in rbac.effective_permissions. The portal never derives
     permissions from the role string. */
  me() {
    return this._req('get', '/api/auth/me');
  },

  changePassword(currentPassword, newPassword) {
    return this._req('post', '/api/auth/change-password', {
      data: { current_password: currentPassword, new_password: newPassword },
    });
  },

  /* profile.manage */
  getProfile() {
    return this._req('get', '/api/profile');
  },
  updateProfile(payload) {
    return this._req('put', '/api/profile', { data: payload });
  },
  /* Marks the session active, which is what feeds `is_online` in the Users
     grid. Sent on a timer, never awaited by anything the user is waiting for. */
  heartbeat(currentPage) {
    return this._req('post', '/api/profile/heartbeat', { data: { current_page: currentPage } });
  },

  /* ==================================================================== */
  /* Dashboards — one endpoint per portal, each its own permission          */
  /* ==================================================================== */

  /* ticket.view — merchant KPIs. Held by admin too, but the response is
     scoped to the caller's merchant_id, which is null for platform staff, so
     wallet/credit come back as 0 and the counters cover EVERY merchant
     (ticket_service.scoped_query lets platform staff see all rows). Read the
     tiles accordingly; the portal only shows the wallet strip to a caller
     that actually has a merchant. */
  merchantDashboard() {
    return this._req('get', '/api/merchant/dashboard');
  },
  /* payment.view — the caller's own financial position, computed by
     finance_service (M4). Existing endpoint, previously unused by this portal:
     the wallet screen was summing one page of payable requests in JavaScript
     and calling the result "Owed now", which under-reported as soon as a
     merchant had more than a page of them. `outstanding` here is the real
     figure, over every billable booking. */
  financePosition() {
    return this._req('get', '/api/merchant/finance/position');
  },
  /* merchant.view — platform-wide counts + recent activity. */
  adminDashboard() {
    return this._req('get', '/api/admin/dashboard');
  },
  /* system.activity.view — admin/merchant headcounts + schema version. */
  superAdminDashboard() {
    return this._req('get', '/api/super-admin/dashboard');
  },

  /* ==================================================================== */
  /* Catalog / inventory — ticket.enquiry                                  */
  /* ==================================================================== */

  /* The ONLY accepted filters are travel_type, origin, destination,
     travel_date, cabin_class, passengers, max_price, airline, q, page,
     page_size. page_size is capped at 100 by the router. There is no stops /
     star-rating / amenity / refundable parameter — anything finer has to be
     narrowed client-side, and the portal says so rather than pretending. */
  searchCatalog(params) {
    return this._req('get', '/api/catalog/search', { params });
  },
  /* passengers drives real per-passenger multiplication server-side; it is
     not a display hint. */
  quote(itemId, passengers) {
    return this._req('get', `/api/catalog/${itemId}/quote`, { params: { passengers } });
  },

  /* ==================================================================== */
  /* Requests — the single table behind Bookings, Requests and Enquiries    */
  /* ==================================================================== */

  /* ticket.view. Filters: request_type, status, travel_type, merchant_id,
     search, date_from, date_to, page, page_size.

     TWO TRAPS, both verified in ticket_service.list_requests:
     1. date_from/date_to filter TRAVEL_DATE, not created_at. A "last 30 days"
        window shaped like a created-date filter returns nothing, because
        everything travels in the future.
     2. merchant_id is ignored unless the caller is platform staff.

     `search` is a genuine server-side search across pnr, request_number,
     booking_reference, ticket_number, title, destination city, and a
     subquery over passenger first name / last name / passport number. That
     is what the global search box uses. */
  listRequests(params) {
    return this._req('get', '/api/requests', { params });
  },

  /* ticket.view. Returns { request, timeline, actions, payments,
     can_download }. `actions` is the server's own list of transitions this
     actor may walk right now — see OPS_TRANSITION_ENDPOINT below for how a
     target status maps onto a route. */
  getRequest(id) {
    return this._req('get', `/api/requests/${id}`);
  },

  /* M7. The invoice PDF, rendered on demand from the booking and its payments.
     `ticket.view` and ticketed/completed only — the server allocates the
     invoice number at issuance, so there is nothing to number before then and
     it answers 409. This screen used to render a permanently disabled Invoice
     button whose tooltip said no endpoint produced one; the endpoint has
     existed since M2. */
  downloadInvoice(requestId) {
    return this._req('get', `/api/requests/${requestId}/invoice`, { responseType: 'blob' });
  },

  /* ticket.request. Creates a DRAFT — nothing is reserved and the approvals
     team cannot see it until submit(). Two steps by design.
     `passengers` entries carry the 14 PassengerInput keys; optional fields
     must be omitted (undefined), not sent as '', because the backend
     distinguishes absent from empty. */
  createRequest({ catalogItemId, passengers, travelDate, returnDate, remarks }) {
    return this._req('post', '/api/requests', {
      data: {
        catalog_item_id: catalogItemId,
        passengers,
        travel_date: travelDate || undefined,
        return_date: returnDate || undefined,
        remarks: remarks || undefined,
      },
    });
  },

  /* ticket.request. Draft only (lifecycle.EDITABLE_STATUSES == {draft}).
     Accepts remarks / travel_date / return_date and nothing else. */
  updateDraft(id, { remarks, travelDate, returnDate }) {
    return this._req('put', `/api/requests/${id}`, {
      data: {
        remarks: remarks ?? undefined,
        travel_date: travelDate || undefined,
        return_date: returnDate || undefined,
      },
    });
  },

  /* ticket.request. Replaces the WHOLE passenger list — send every passenger
     you want to keep, not just the edited one. */
  replacePassengers(id, passengers) {
    return this._req('put', `/api/requests/${id}/passengers`, { data: { passengers } });
  },

  submitRequest(id) {
    return this._req('post', `/api/requests/${id}/submit`, { data: {} });
  },
  cancelRequest(id, reason) {
    return this._req('post', `/api/requests/${id}/cancel`, { data: { reason } });
  },

  /* ==================================================================== */
  /* Approval / issuing — platform staff                                   */
  /* ==================================================================== */

  /* ticket.approve. Walks pending_approval -> in_review -> approved ->
     payment_pending in ONE call (ticket_service.approve_request), which is
     why in_review and payment_pending have no endpoints of their own even
     though they appear in the `actions` list. `final_amount` overwrites
     total_amount — this is where a quoted figure becomes payable. */
  approveRequest(id, { finalAmount, note } = {}) {
    return this._req('post', `/api/admin/requests/${id}/approve`, {
      data: {
        final_amount: finalAmount === '' || finalAmount == null ? undefined : Number(finalAmount),
        note: note || undefined,
      },
    });
  },
  /* ticket.approve. Changes what is owed on a booking that is already
     Payment Pending, without moving it — approve cannot be called a second
     time, because Payment Pending has no edge back to Approved. Both fields
     are mandatory server-side; the merchant is notified of the change. */
  repriceRequest(id, { amount, reason } = {}) {
    return this._req('post', `/api/admin/requests/${id}/reprice`, {
      /* M4: the string as typed. The endpoint's schema is `Decimal`; a float
         on the wire is the rounding error this milestone removes. */
      data: { amount: String(amount ?? '').trim(), reason },
    });
  },
  /* ticket.reject. Reason is mandatory server-side (400 without it). */
  rejectRequest(id, reason) {
    return this._req('post', `/api/admin/requests/${id}/reject`, { data: { reason } });
  },
  /* ticket.issue. Only from `paid`. */
  issueTicket(id) {
    return this._req('post', `/api/admin/requests/${id}/issue-ticket`, { data: {} });
  },
  /* `completeRequest` was removed with POST /api/admin/requests/{id}/complete.
     A booking is completed by the backend once its scheduled travel has
     finished, never by a caller — see backend booking_completion_service. */

  /* merchant.view OR ticket.view. Merged queue of pending merchants and
     pending requests in one discriminated list: `kind` is 'merchant' or
     'request', and `id` means merchant_id or request_id accordingly.

     NOTE the date filters are inconsistent by construction — for merchant
     rows they match created_at, for request rows they go through
     list_requests and therefore match travel_date. */
  approvalQueue(params) {
    return this._req('get', '/api/admin/approval-queue', { params });
  },

  /* ==================================================================== */
  /* Service requests                                                      */
  /* ==================================================================== */

  /* servicerequest.create. Only against a BOOKING that is already at
     approved / payment_pending / paid / ticket_issued / completed.
     `details` shape depends on request_type:
        cancellation            { passenger_ids: [int] }
        date_change             { passenger_id: int, new_travel_date: 'YYYY-MM-DD' }
        refund                  { amount: number }
        passenger_modification  { passenger_id: int, changes: {...} }
        extra_baggage/meal/seat  free-form
     Created at draft then immediately transitioned to pending_approval by
     the service.

     IT IS NOT ON THE STAFF QUEUE YET. Since 2026-08-01 every service request
     waits for a manager of the raising merchant first — the response carries
     `manager_state: 'pending'` and reads "Under Manager Approval" until they
     sign it off through /api/manager/service-requests. A request raised BY a
     manager is stamped approved on the spot. */
  createServiceRequest({ bookingId, requestType, remarks, details }) {
    return this._req('post', '/api/service-requests', {
      data: { booking_id: bookingId, request_type: requestType, remarks, details },
    });
  },

  /* servicerequest.manage. approve=false needs a reason. Approving moves the
     request to `approved` — it does NOT itself change the parent booking.

     409 while the raising merchant's own manager has not signed it off; see
     createServiceRequest above. */
  resolveServiceRequest(id, { approve, reason }) {
    return this._req('post', `/api/admin/service-requests/${id}/resolve`, {
      data: { approve, reason: reason || undefined },
    });
  },

  /* ==================================================================== */
  /* Payments                                                              */
  /* ==================================================================== */

  /* payment.pay. record_payment gates on status == payment_pending ONLY — it
     does not check request_type, so an approved service request is payable
     through the same route. Rejects amount <= 0 with a 400. Lands as
     `pending` until an admin verifies it. */
  payRequest(id, { amount, method, transactionId }) {
    return this._req('post', `/api/requests/${id}/pay`, {
      data: { amount, method, transaction_id: transactionId || undefined },
    });
  },

  /* payment.view — every payment platform-wide. Filters: status, merchant_id,
     date_from, date_to (both against created_at here, unlike /api/requests),
     search (transaction_id or method only).

     PaymentSummary carries NO merchant or booking reference — id, amount,
     currency, method, transaction_id, status, paid_date and nothing else.
     The link from a payment back to its booking only exists in the other
     direction, via getRequest(id).payments. The grid says so rather than
     leaving an operator guessing whose money this is. */
  listPayments(params) {
    return this._req('get', '/api/admin/payments', { params });
  },
  /* payment.verify — the verification queue (payment_status == pending). */
  pendingPayments(params) {
    return this._req('get', '/api/admin/payments/pending', { params });
  },
  /* payment.verify. approve=true moves the linked request to `paid`;
     approve=false marks the payment failed and leaves the request where it
     is, so the merchant can pay again. */
  verifyPayment(paymentId, { approve, note }) {
    return this._req('post', `/api/admin/payments/${paymentId}/verify`, {
      data: { approve, note: note || undefined },
    });
  },
  /* payment.manage. Against a successful payment only. */
  refundPayment(paymentId, { amount, reason }) {
    return this._req('post', `/api/admin/payments/${paymentId}/refund`, {
      data: { amount, reason },
    });
  },

  /* ==================================================================== */
  /* Merchants — merchant.* permissions                                    */
  /* ==================================================================== */

  listMerchants(params) {
    return this._req('get', '/api/admin/merchants', { params });
  },
  getMerchant(id) {
    return this._req('get', `/api/admin/merchants/${id}`);
  },
  /* merchant.create — also creates the company's first login and returns a
     one-time temporary password that is never retrievable again. */
  createMerchant(payload) {
    return this._req('post', '/api/admin/merchants', { data: payload });
  },
  /* merchant.edit — only the fields present in the body change. */
  updateMerchant(id, payload) {
    return this._req('put', `/api/admin/merchants/${id}`, { data: payload });
  },
  /* merchant.approve — a company's staff cannot sign in until this happens. */
  approveMerchant(id) {
    return this._req('post', `/api/admin/merchants/${id}/approve`, { data: {} });
  },
  /* merchant.suspend — status is one of pending_approval / active /
     inactive / suspended. There is no "reject a merchant" route; declining
     an application means setting it inactive. */
  setMerchantStatus(id, status) {
    return this._req('patch', `/api/admin/merchants/${id}/status`, { data: { status } });
  },
  /* merchant_user.manage */
  merchantUsers(id, params) {
    return this._req('get', `/api/admin/merchants/${id}/users`, { params });
  },
  resetMerchantUserPassword(merchantId, userId) {
    return this._req('post', `/api/admin/merchants/${merchantId}/users/${userId}/reset-password`, { data: {} });
  },

  /* ==================================================================== */
  /* Users                                                                 */
  /* ==================================================================== */

  /* merchant_user.manage — cross-merchant list. Search covers full_name and
     email only (NOT phone). */
  listUsers(params) {
    return this._req('get', '/api/admin/users', { params });
  },

  /* merchant_user.manage, scoped to the caller's own company. Useless to
     platform staff (merchant_id is null), so the portal hides the tab for
     an account with no merchant rather than showing an empty table. */
  listTeam(params) {
    return this._req('get', '/api/merchant/team', { params });
  },
  getTeamMember(id) {
    return this._req('get', `/api/merchant/team/${id}`);
  },
  /* merchant_user.create. role must be merchant_admin or merchant_user. */
  createTeamMember(payload) {
    return this._req('post', '/api/merchant/team', { data: payload });
  },
  updateTeamMember(id, payload) {
    return this._req('put', `/api/merchant/team/${id}`, { data: payload });
  },
  setTeamMemberStatus(id, status) {
    return this._req('patch', `/api/merchant/team/${id}/status`, { data: { status } });
  },
  resetTeamMemberPassword(id) {
    return this._req('post', `/api/merchant/team/${id}/reset-password`, { data: {} });
  },

  /* ==================================================================== */
  /* Administrators — admin.* (super admin only)                           */
  /* ==================================================================== */

  listAdmins(params) {
    return this._req('get', '/api/super-admin/admins', { params });
  },
  getAdmin(id) {
    return this._req('get', `/api/super-admin/admins/${id}`);
  },
  createAdmin(payload) {
    return this._req('post', '/api/super-admin/admins', { data: payload });
  },
  updateAdmin(id, payload) {
    return this._req('put', `/api/super-admin/admins/${id}`, { data: payload });
  },
  setAdminStatus(id, status) {
    return this._req('patch', `/api/super-admin/admins/${id}/status`, { data: { status } });
  },
  resetAdminPassword(id) {
    return this._req('post', `/api/super-admin/admins/${id}/reset-password`, { data: {} });
  },
  deleteAdmin(id) {
    return this._req('delete', `/api/super-admin/admins/${id}`);
  },
  /* Returns { admin_id, role_defaults, extra_grants, effective }. Only
     extra_grants is writable — the role -> permission matrix itself is fixed
     by design (rbac.role_permission_matrix's docstring is explicit that the
     separation is the point, not a gap to fill with a role editor). */
  adminPermissions(id) {
    return this._req('get', `/api/super-admin/admins/${id}/permissions`);
  },
  setAdminPermissions(id, extraGrants) {
    return this._req('put', `/api/super-admin/admins/${id}/permissions`, {
      data: { extra_grants: extraGrants },
    });
  },
  /* system.activity.view — the fixed matrix, read-only. */
  permissionMatrix() {
    return this._req('get', '/api/super-admin/permissions/matrix');
  },

  /* ==================================================================== */
  /* System logs                                                           */
  /* ==================================================================== */

  /* system.activity.view. Held by ADMIN as well as super admin, so the
     activity log is not a super-admin-only screen. */
  activityLog(params) {
    return this._req('get', '/api/super-admin/activity', { params });
  },
  activityFilters() {
    return this._req('get', '/api/super-admin/activity/filters');
  },
  /* audit.view. Row-level before/after JSONB. No `search` parameter —
     filter by table / operation / changed_by / date instead. */
  auditLogs(params) {
    return this._req('get', '/api/super-admin/audit-logs', { params });
  },
  auditTables() {
    return this._req('get', '/api/super-admin/audit-logs/tables');
  },
  /* system.activity.view — read-only config snapshot. */
  systemInfo() {
    return this._req('get', '/api/super-admin/system-info');
  },

  /* ==================================================================== */
  /* Reports                                                               */
  /* ==================================================================== */

  /* report.export. Returns a Blob; the caller owns the object URL and must
     revoke it. type=bookings|service_requests|payments,
     format=csv|xlsx|pdf. bookings/service_requests honour the same
     date/search/status semantics as /api/requests (so date_from is a TRAVEL
     date); payments only honours date_from/date_to/merchant_id and ignores
     status and search. */
  exportReport(params) {
    return this._req('get', '/api/reports/export', { params, responseType: 'blob' });
  },

  /* Role-gated to super_admin/admin rather than permission-gated, on purpose:
     report.view is also held by merchants but for their own scoped data, not
     this cross-merchant rollup. */
  globalSummary() {
    return this._req('get', '/api/super-admin/reports/summary');
  },

  /* ==================================================================== */
  /* Notifications                                                         */
  /* ==================================================================== */

  listNotifications(params) {
    return this._req('get', '/api/notifications', { params });
  },
  /* Both unread-count endpoints return { count: n }. */
  notificationUnreadCount() {
    return this._req('get', '/api/notifications/unread-count');
  },
  markNotificationRead(id) {
    return this._req('patch', `/api/notifications/${id}/read`, { data: {} });
  },
  markAllNotificationsRead() {
    return this._req('post', '/api/notifications/read-all', { data: {} });
  },
  /* notification.send — to every user of the named merchants, or every
     active merchant when merchant_ids is omitted. A merchant with
     notifications switched off in its communication settings is skipped. */
  broadcast({ merchantIds, title, message }) {
    return this._req('post', '/api/admin/notifications/broadcast', {
      data: { merchant_ids: merchantIds && merchantIds.length ? merchantIds : undefined, title, message },
    });
  },

  /* ==================================================================== */
  /* Communication settings — notification.send                            */
  /* ==================================================================== */

  communicationSettings(merchantId) {
    return this._req('get', `/api/admin/communication-settings/${merchantId}`);
  },
  updateCommunicationSettings(merchantId, payload) {
    return this._req('put', `/api/admin/communication-settings/${merchantId}`, { data: payload });
  },

  /* ==================================================================== */
  /* Support / live chat                                                   */
  /* ==================================================================== */

  /* chat.view. A merchant sees its own threads; platform staff see all.
     `status` takes a RequestStatus value (threads reuse the request
     lifecycle: draft/pending_approval = open, in_review = claimed,
     completed = resolved). */
  listThreads(params) {
    return this._req('get', '/api/support/threads', { params });
  },
  getThread(id) {
    return this._req('get', `/api/support/threads/${id}`);
  },
  /* chat.create — merchant side only. */
  openThread({ subject, message }) {
    return this._req('post', '/api/support/threads', { data: { subject, message } });
  },
  /* chat.create OR chat.manage. A super admin holds neither, so it has
     read-only visibility of the queue by design. An admin's first reply
     auto-claims the thread. */
  sendThreadMessage(id, message) {
    return this._req('post', `/api/support/threads/${id}/messages`, { data: { message } });
  },
  claimThread(id) {
    return this._req('post', `/api/support/threads/${id}/claim`, { data: {} });
  },
  resolveThread(id) {
    return this._req('post', `/api/support/threads/${id}/resolve`, { data: {} });
  },

  /* chat.manage. Re-files a thread's priority and category — the desk's
     judgement, not the raiser's. Omitted fields are left alone server-side, so
     sending only a priority cannot clear a category. */
  triageThread(id, { priority, category } = {}) {
    return this._req('patch', `/api/support/threads/${id}/triage`, {
      data: { priority: priority || undefined, category: category || undefined },
    });
  },

  /* chat.manage AND a platform-staff account. INTERNAL NOTES ARE NEVER SHOWN
     TO THE MERCHANT — nothing merchant-facing calls these, and the server
     refuses them for a merchant account regardless of what a client asks. */
  listThreadNotes(id) {
    return this._req('get', `/api/support/threads/${id}/notes`);
  },
  addThreadNote(id, body) {
    return this._req('post', `/api/support/threads/${id}/notes`, { data: { body } });
  },

  /* Files shared on a conversation. Metadata only — bytes come from
     downloadDocument, which re-checks scope on every read. */
  listThreadDocuments(id) {
    return this._req('get', `/api/support/threads/${id}/documents`);
  },
  /* `ticket.view`, plus a server-side re-check that the document belongs to a
     merchant this caller may see. Downloads are authenticated, so an
     attachment can never be a plain href — the blob is pulled with the bearer
     token and handed over as an object URL. CALLERS MUST REVOKE IT. */
  async downloadDocument(documentId) {
    const blob = await this._req('get', `/api/documents/${documentId}/download`, {
      responseType: 'blob',
    });
    return URL.createObjectURL(blob);
  },
  /* Multipart, so this bypasses _req's JSON shape — the browser must set its
     own boundary. Returns the whole thread, like sendThreadMessage. */
  uploadThreadDocument(id, file) {
    const form = new FormData();
    form.append('file', file);
    return axios.post(`${OPS_API_BASE}/api/support/threads/${id}/documents`, form, {
      headers: opsAuthHeaders(),
    }).then(r => r.data);
  },

  chatUnreadCount() {
    return this._req('get', '/api/support/unread-count');
  },
};

/* ===========================================================================
   Vocabulary — taken from the enums the backend actually stores. A screen
   that invents its own status string does not merely mislabel a row, it
   silently filters to nothing (or 422s on an unknown enum member).
   =========================================================================== */

/* request_status_enum, in lifecycle order. Note TICKET_ISSUED is
   'ticket_issued' — not 'ticketed'. */
const OPS_REQUEST_STATUSES = [
  'draft', 'submitted', 'pending_approval', 'in_review', 'approved',
  'payment_pending', 'paid', 'ticket_issued', 'verified', 'completed',
  'rejected', 'cancelled',
];

/* lifecycle.SPEC_LABELS — the spec's own wording for each status, so the
   grid and the server-rendered timeline agree. */
const OPS_STATUS_LABEL = {
  draft: 'Created',
  submitted: 'Submitted',
  pending_approval: 'Pending',
  in_review: 'Under Review',
  approved: 'Approved',
  payment_pending: 'Payment Pending',
  paid: 'Paid',
  ticket_issued: 'Ticket Issued',
  verified: 'Verified',
  completed: 'Completed',
  rejected: 'Rejected',
  cancelled: 'Cancelled',
};

/* lifecycle.HAPPY_PATH — drives the progress rail in the request drawer. */
const OPS_HAPPY_PATH = [
  'draft', 'pending_approval', 'in_review', 'approved',
  'payment_pending', 'paid', 'ticket_issued', 'completed',
];

/* request_type_enum. catalog_item is excluded from every request list by
   ticket_service.scoped_query (it is how inventory itself is stored), so it
   is deliberately absent from the filter options. */
const OPS_SERVICE_REQUEST_TYPES = [
  'cancellation', 'date_change', 'refund', 'passenger_modification',
  'extra_baggage', 'meal', 'seat',
];
const OPS_REQUEST_TYPES = ['booking', ...OPS_SERVICE_REQUEST_TYPES, 'ticket_enquiry', 'support_ticket', 'live_chat'];

const OPS_TRAVEL_TYPES = ['flight', 'hotel', 'cruise', 'package'];
const OPS_PAYMENT_STATUSES = ['pending', 'processing', 'success', 'failed', 'refunded', 'partially_refunded'];
const OPS_USER_STATUSES = ['active', 'inactive', 'blocked', 'suspended'];
const OPS_MERCHANT_STATUSES = ['pending_approval', 'active', 'inactive', 'suspended'];
const OPS_COMPANY_TYPES = ['gaming_company', 'corporate_company', 'travel_agency', 'business_partner', 'direct_customer'];
const OPS_MERCHANT_ROLES = ['manager', 'supervisor', 'operator', 'finance', 'data_operator'];
const OPS_USER_ROLES = ['super_admin', 'admin', 'merchant_admin', 'merchant_user', 'customer'];
const OPS_PRIORITIES = ['low', 'normal', 'high', 'urgent'];
const OPS_CABINS = ['economy', 'premium_economy', 'business', 'first'];

/* Which route walks a request to a given status.
   `getRequest().actions` returns TARGET STATUSES, not endpoints, and two of
   them have no endpoint of their own:
     in_review       — approve_request() walks pending_approval -> in_review
                       itself before approving, so there is nothing to call.
     payment_pending — the same call continues approved -> payment_pending.
   Rendering a button for either would produce a 404, so both map to null and
   the drawer skips them.

   `completed` is now a third one, for a different reason: it is no longer an
   action at all. A booking completes when its scheduled travel has finished,
   swept by the backend, so the edge never appears in `actions` and nothing can
   walk it. It is mapped to null rather than deleted from this table so that a
   stale `actions` payload from a cached page cannot fall through to
   `OpsApi[undefined]` — the drawer skips a null, and would throw on a missing
   key. */
const OPS_TRANSITION_ENDPOINT = {
  pending_approval: { fn: 'submitRequest', label: 'Submit for approval', permission: 'ticket.request' },
  cancelled: { fn: 'cancelRequest', label: 'Cancel request', permission: 'ticket.request', reason: true },
  approved: { fn: 'approveRequest', label: 'Approve', permission: 'ticket.approve' },
  rejected: { fn: 'rejectRequest', label: 'Reject', permission: 'ticket.reject', reason: true },
  ticket_issued: { fn: 'issueTicket', label: 'Issue ticket', permission: 'ticket.issue' },
  completed: null,
  in_review: null,
  payment_pending: null,
  /* `paid` is reached by VERIFYING A PAYMENT, which is keyed by payment_id,
     not request_id — the drawer offers it on the payment row instead. */
  paid: null,
};
